### ISSUE TITLE
request to add watched time 

### ISSUE THREAD

**Issue by Rkso0** [ilmuneraka/letterboxd-friends-ranker#1]
Hi, I was wondering if there is any chance to add the watched time to the statistics. Thank you for keeping it updated.

**Comment by alfianalytics** [comment]
Maybe I could add the total duration of the movies you have watched, but
excluding the rewatches because I scrape from movie list, not diaries.
Thanks for the suggestion by the way, I was thinking adding country,
language, and themes too actually.

**Comment by Rkso0** [comment]
> Maybe I could add the total duration of the movies you have watched, but excluding the rewatches because I scrape from movie list, not diaries.

Yes, it's fine. Also, if you need more ideas for the duration of the movies, a paragraph about films that are less than 90 minutes or longer than 180 minutes could be helpful. Thank you again for your quick response.

**Comment by alfianalytics** [comment]
I've already added the runtime and themes too by now. You should check it
out

**Comment by Rkso0** [comment]
It is great. thanks
